name: Build, analyse and test

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: ramsey/composer-install@v2

      - name: rector downgrade
        run: 'php vendor/bin/rector process --config rector-downgrade.php'

      - uses: actions/upload-artifact@master
        with:
          name: build
          path: |
            src
            tests
          if-no-files-found: error

  analyse:
    strategy:
      fail-fast: false
      matrix:
        php_version: [ '8.0', '8.1' ]

    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none

      - uses: actions/download-artifact@master
        with:
          name: build
          path: .

      - uses: ramsey/composer-install@v2

      - name: Run static analysis
        run: php vendor/bin/phpstan analyse

  test:
    needs:
      - build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: [ '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none

      - uses: actions/download-artifact@master
        with:
          name: build
          path: .

      - uses: ramsey/composer-install@v2

      - name: Run testsuite
        run: php vendor/bin/phpunit tests

  copy:
    needs:
      - analyse
      - test

    # Don't run on forks.
    if: |
      github.repository == 'N-Silbernagel/AccumulatePHP-src' &&
      (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@master
        with:
          name: "build"
          path: build-artifact

      - name: "Checkout remote repository"
        uses: "actions/checkout@v3"
        with:
          repository: N-Silbernagel/AccumulatePHP
          path: remote-repository
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: "Copy build files to remote repository"
        run: cp -a build-artifact/. remote-repository

      - name: "Remove unwanted files from repository"
        working-directory: remote-repository
        run: rm -rf .github .idea docker rector-downgrade.php


      - name: "Setup Git"
        working-directory: remote-repository
        run: |
          git config user.email "6422477+N-Silbernagel@users.noreply.github.com"
          git config user.name "N-Silbernagel"

      - name: "Get Git log"
        id: git-log
        run: echo ::set-output name=log::$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='%H %s' | sed -e 's/^/https:\/\/github.com\/N-Silbernagel\/AccumulatePHP\/commit\//')

      - name: "Commit to remote - master"
        working-directory: remote-repository
        if: "github.ref == 'refs/heads/master'"
        run: |
          git add --all
          git commit -m "Updated AccumulatePHP to commit ${{ github.event.after }}" -m "${{ steps.git-log.outputs.log }}"
          git push --quiet origin master

      - name: "Commit to remote - tag"
        working-directory: remote-repository
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          git add --all
          git commit -m "AccumulatePHP ${GITHUB_REF#refs/tags/}" -m "${{ steps.git-log.outputs.log }}"
          git push --quiet origin master
          git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
          git push --quiet origin ${GITHUB_REF#refs/tags/}
